### ISSUE TITLE
Teach with vanilla Git commands (not aliases)?

### ISSUE THREAD

**Issue by seananderson** [cgrandin/git-course#27]
My vote would be to teach with vanilla Git commands so that people learn the basics that will work everywhere. Then later teach how to create, edit, and use aliases. Otherwise people don't learn a cognitive model of the basics and confuse what's an alias in their current setup with what's a Git command.

I.e. teach

```
git status
git add myfile.txt
git commit
# or
git commit -m "My message"
git checkout ...
etc.
```

**Comment by cgrandin** [comment]
I agree. We can introduce aliases later perhaps, i.e. how to make your own and where they go.

I'll change slides to standard commands.

**Comment by andrew-edwards** [comment]
Sorry, but I really disagree - what we have has worked last time and is simpler. I think we can more strongly emphasise that we have aliases (so you can't just google 'git com'). I know that I'll get in a mess if I have to start using 
```
git commit -a -m "message"
```
instead of just
```
git com "message"
```

We could certainly add a slide (we only have maybe a bullet point now) emphasising that these are aliases. I hadn't realised until recently that `git com` is actually adding each time - but that hasn't impacted my workflow. We do need to keep it as simple as possible. Lots of people don't like using command lines anyway, so the shorter the better....
